name: Motor de Extraccion DIAN
on:
  workflow_dispatch: # Esto activa el botón manual para que tú lo inicies

jobs:
  descarga_masiva:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Copiando el codigo
        uses: actions/checkout@v4

      - name: 2. Configurando Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Instalando herramientas de navegacion
        run: |
          pip install playwright pandas
          playwright install chromium
          playwright install-deps

      - name: 4. Ejecutando extraccion de facturas
        run: python main.py

      - name: 5. Entregando archivos PDF
        uses: actions/upload-artifact@v4
        with:
          name: Facturas_Descargadas_DIAN
          path: ./facturas/
