name: Motor de Extraccion DIAN
on:
  workflow_dispatch:

jobs:
  descarga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar Playwright
        run: |
          pip install playwright pandas
          python -m playwright install chromium --with-deps
      - name: Ejecutar Extraccion
        run: python main.py
      - name: Subir Resultados
        uses: actions/upload-artifact@v4
        if: always() # Esto obliga a buscar la carpeta aunque haya errores
        with:
          name: facturas-pdf
          path: facturas/
