name: Motor de Extraccion DIAN
on:
  workflow_dispatch:

jobs:
  descarga:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Esto acelera las prÃ³ximas ejecuciones
      - name: Instalar Playwright
        run: |
          pip install playwright pandas
          python -m playwright install chromium --with-deps
          echo ">>> INSTALACION COMPLETADA <<<"
      - name: Ejecutar Extraccion
        run: python main.py
