name: Motor de Extraccion
on:
  workflow_dispatch: # ESTO es lo que crea el bot√≥n manual

jobs:
  ejecucion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar Navegador
        run: |
          pip install playwright
          playwright install chromium
          playwright install-deps
      - name: Ejecutar Script
        run: python main.py
