name: Ejecutor DIAN
on:
  workflow_dispatch: # Esto activa el botón para que tú lo corras cuando quieras

jobs:
  ejecucion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - setup-python: '3.10'
      - name: Instalar Herramientas
        run: |
          pip install playwright
          playwright install chromium
          playwright install-deps
      - name: Correr Script
        run: python main.py
